name: smartgarden_v1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  firebase_database: ^12.0.2
  google_fonts: ^6.0.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  bootstrap_icons: ^1.11.3
  image_picker: ^1.2.0
  uuid: ^4.5.1
  camera: ^0.11.2       
  permission_handler: ^12.0.1
  path_provider: ^2.0.11
  http: ^1.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Logov1.1.png
    - assets/images/backgroundfolhas.jpg
    - assets/icons/google.png
    - assets/images/cactus.png
    - assets/images/jiboia.png
    - assets/images/orquidea.png
    - assets/images/samambaia.png
    - assets/icons/Scan.png
