// File generated by FlutterFire CLI.

// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_T9fx70WG9YQE75_QWtKw8bgt2BA_cRM',
    appId: '1:639049589407:web:2cad12b29680a2975af8aa',
    messagingSenderId: '639049589407',
    projectId: 'smartgarden-d85ce',
    authDomain: 'smartgarden-d85ce.firebaseapp.com',
    storageBucket: 'smartgarden-d85ce.firebasestorage.app',
    measurementId: 'G-9LHL384SV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKj_hW82LixwiczRnKfqDE-eQDR6IWXVc',
    appId: '1:639049589407:android:d80048c30e51a4865af8aa',
    messagingSenderId: '639049589407',
    projectId: 'smartgarden-d85ce',
    storageBucket: 'smartgarden-d85ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq5VkJlUFjo_cxB9ClpRmnATXvyy9ByWw',
    appId: '1:639049589407:ios:97f429a02c8279425af8aa',
    messagingSenderId: '639049589407',
    projectId: 'smartgarden-d85ce',
    storageBucket: 'smartgarden-d85ce.firebasestorage.app',
    iosBundleId: 'com.example.smartgardenRoot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2KrNViCylCmYY-PeIwYW0yC28xI17vaI',
    appId: '1:833531454485:ios:8724f1e3d7987221925a1c',
    messagingSenderId: '833531454485',
    projectId: 'smart-garden-4e64d',
    databaseURL: 'https://smart-garden-4e64d-default-rtdb.firebaseio.com',
    storageBucket: 'smart-garden-4e64d.firebasestorage.app',
    iosBundleId: 'com.example.smartgardenRoot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_kSMnq2Nfm4nsO8W6xYQ4amINOj7PZAw',
    appId: '1:833531454485:web:beb31e44c3504c02925a1c',
    messagingSenderId: '833531454485',
    projectId: 'smart-garden-4e64d',
    authDomain: 'smart-garden-4e64d.firebaseapp.com',
    databaseURL: 'https://smart-garden-4e64d-default-rtdb.firebaseio.com',
    storageBucket: 'smart-garden-4e64d.firebasestorage.app',
  );
}