// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_kSMnq2Nfm4nsO8W6xYQ4amINOj7PZAw',
    appId: '1:833531454485:web:a06958c6bbca1beb925a1c',
    messagingSenderId: '833531454485',
    projectId: 'smart-garden-4e64d',
    authDomain: 'smart-garden-4e64d.firebaseapp.com',
    databaseURL: 'https://smart-garden-4e64d-default-rtdb.firebaseio.com',
    storageBucket: 'smart-garden-4e64d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj3McAUpqUaf-FGP_ZrtmDOs1u5_M5QzA',
    appId: '1:833531454485:android:7f3cb2ada0403ed9925a1c',
    messagingSenderId: '833531454485',
    projectId: 'smart-garden-4e64d',
    databaseURL: 'https://smart-garden-4e64d-default-rtdb.firebaseio.com',
    storageBucket: 'smart-garden-4e64d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2KrNViCylCmYY-PeIwYW0yC28xI17vaI',
    appId: '1:833531454485:ios:8724f1e3d7987221925a1c',
    messagingSenderId: '833531454485',
    projectId: 'smart-garden-4e64d',
    databaseURL: 'https://smart-garden-4e64d-default-rtdb.firebaseio.com',
    storageBucket: 'smart-garden-4e64d.firebasestorage.app',
    iosBundleId: 'com.example.smartgardenRoot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2KrNViCylCmYY-PeIwYW0yC28xI17vaI',
    appId: '1:833531454485:ios:8724f1e3d7987221925a1c',
    messagingSenderId: '833531454485',
    projectId: 'smart-garden-4e64d',
    databaseURL: 'https://smart-garden-4e64d-default-rtdb.firebaseio.com',
    storageBucket: 'smart-garden-4e64d.firebasestorage.app',
    iosBundleId: 'com.example.smartgardenRoot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_kSMnq2Nfm4nsO8W6xYQ4amINOj7PZAw',
    appId: '1:833531454485:web:beb31e44c3504c02925a1c',
    messagingSenderId: '833531454485',
    projectId: 'smart-garden-4e64d',
    authDomain: 'smart-garden-4e64d.firebaseapp.com',
    databaseURL: 'https://smart-garden-4e64d-default-rtdb.firebaseio.com',
    storageBucket: 'smart-garden-4e64d.firebasestorage.app',
  );
}
